# Generated by Django 3.1.3 on 2020-11-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20201122_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='title',
        ),
    ]
