# Generated by Django 3.1.3 on 2020-11-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20201122_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(),
        ),
    ]
