# Generated by Django 3.1.3 on 2020-11-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_auto_20201122_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='image',
            name='profile_image',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.profile'),
            preserve_default=False,
        ),
    ]
